logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/realms/demo/protocol/openid-connect/certs
